name: nfsee
description: An NFC data dumper.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_nfc_kit:
  interactive_webview:
  cupertino_icons:
  moor:
  moor_ffi:
  path_provider:
  path:
  intl:
  intl_translation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
