name: nfsee
description: An NFC data dumper.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  interactive_webview:
  flutter_nfc_kit:
    git:
      url: https://github.com/nfcim/flutter_nfc_kit.git
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
