name: nfsee
description: An NFC data dumper.

version: 2.1.0+5

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_nfc_kit: "^2.2.0"
  interactive_webview_null_safety: "^0.2.4"
  cupertino_icons: "^0.1.3"
  moor: "^4.5.0"
  sqlite3_flutter_libs: "^0.5.0"
  path_provider: "^1.6.0"
  path: "^1.6.4"
  intl: "^0.17.0"
  package_info: "^2.0.2"
  url_launcher: "^5.7.10"
  webview_flutter: "^1.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: "^4.0.0"
  build_runner: "^1.7.4"
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards/
    - assets/icons/
    - assets/html/

flutter_intl:
  enabled: true

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/icons/icon_full.png"
